pipeline {
  agent any
  environment {
    ECR_REPOSITORY = credentials('ECR_REPOSITORY')
    AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
    AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
  }
  
  stages {
    stage('Continuous Integration') {
      steps {
        script {
          echo "Linting repository"
          echo "Running unit tests"
        }
      }
    }

    stage('Login to ECR') {
      steps {
        script {
          sh '''
            aws ecr get-login-password --region ap-south-2 \
            | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-2.amazonaws.com
          '''
        }
      }
    }

    stage('Build Image') {
      steps {
        script {
          sh 'docker build -t ${ECR_REPOSITORY}:latest .'
        }
      }
    }

    stage('Push Image') {
      steps {
        script {
          sh 'docker push ${ECR_REPOSITORY}:latest'
        }
      }
    }

    stage('Continuous Deployment') {
      steps {
        sshagent(['ssh_key']) {
          sh '''
            ssh -o StrictHostKeyChecking=no -l ubuntu 98.130.33.228 "
              cd /home/ubuntu/ &&
              wget -O docker-compose.yaml https://raw.githubusercontent.com/Roniwatson4222/MLOPs-DEEP-LEARNING-PROJECT/refs/heads/main/docker-compose.yaml &&
              aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-2.amazonaws.com &&
              IMAGE_NAME=${ECR_REPOSITORY}:latest docker compose pull &&
              IMAGE_NAME=${ECR_REPOSITORY}:latest docker compose up -d --force-recreate
            "
          '''
        }
      }
    }

    stage('Verify Deployment') {
      steps {
        sshagent(['ssh_key']) {
          sh '''
            ssh -o StrictHostKeyChecking=no -l ubuntu 98.130.33.228 "
              cd /home/ubuntu/ &&
              docker compose ps &&
              docker inspect --format='{{json .State.Health}}' $(docker compose ps -q application)
            "
          '''
        }
      }
    }
  }

  post {
    always {
      sh 'docker system prune -f'
    }
  }
}
